"""Generate analysis reports"""
import pandas as pd
from datetime import datetime
from pathlib import Path
from metrics_calculator import PartitionMetrics

def generate_markdown_report(df: pd.DataFrame, output_path: str = None) -> str:
    """Generate Markdown report"""
    metrics = PartitionMetrics(df)
    summary = metrics.get_summary()
    
    report = f"""
# Block Partitioning Analysis Report
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Executive Summary
- **Total Coding Units:** {summary['total_cus']:,}
- **Frames Analyzed:** {summary['total_frames']}
- **Average CUs/Frame:** {summary['cus_per_frame']:.2f}
- **Frame Coverage:** {metrics.frame_coverage():.2f}%

## Partition Structure
### QT-MTT Depths
- **Max QT Depth:** {summary['max_qt_depth']}
- **Max MTT Depth:** {summary['max_mtt_depth']}
- **Max Total Depth:** {summary['max_total_depth']}

### Block Sizes
- **Average Block Size:** {summary['avg_block_size']:.2f} pixels²
- **Most Common Size:** {metrics.get_block_size_distribution().index[0]}

## Prediction Modes
- **Intra Blocks:** {summary['intra_ratio']:.2f}%
- **Inter Blocks:** {summary['inter_ratio']:.2f}%

## Block Distribution
{metrics.get_block_size_summary()}

---
*This report was auto-generated by Block Partitioning Analyzer*
"""
    
    if output_path:
        with open(output_path, 'w') as f:
            f.write(report)
    
    return report

def generate_csv_summary(df: pd.DataFrame, output_path: str = None) -> pd.DataFrame:
    """Generate CSV summary"""
    metrics = PartitionMetrics(df)
    
    summary_data = []
    for poc in sorted(df['POC'].unique()):
        frame_stats = metrics.get_frame_stats(poc)
        summary_data.append(frame_stats)
    
    summary_df = pd.DataFrame(summary_data)
    
    if output_path:
        summary_df.to_csv(output_path, index=False)
    
    return summary_df